# linkerd config for linker-to-linker mode
# routes from port 4140 on source node to 4141 on destination node

admin:
  ip: 0.0.0.0
  port: 9990

usage:
  orgId: alextanhongpin
  enabled: false

routers:
- protocol: h2
  label: h2-ingress
  servers:
  - port: 4140
    ip: 0.0.0.0
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd/4100
    namespace: ingress

- protocol: h2
  label: h2-outgress
  servers:
  - port: 4433
    ip: 0.0.0.0
  identifier:
    kind: io.l5d.header.path
    segments: 1
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd/4100
    namespace: outgress