admin:
  ip: 0.0.0.0
  port: 9991

# Uncomment to enable in-memory storage. NOTE: Don't use this in production!
storage:
  kind: io.l5d.inMemory
  namespaces:
    ingress: |
      /l5d => /$/inet/linkerd/4433; # /l5d/4140/linkerd => /$/inet/linkerd/4433
      /svc => /$/io.buoyant.porthostPfx/l5d; # /svc/linkerd:4140 -> /l5d/4140/linkerd/
    outgress: |
      /srv/Echo => /$/inet/server/50051 & /$/inet/server2/50052;
      /svc => /$/io.buoyant.http.domainToPathPfx/srv; # /svc/echo.Echo -> /srv/Echo/echo

interfaces:
  # used by linkerds to receive updates
  - kind: io.l5d.thriftNameInterpreter
    ip: 0.0.0.0
    port: 4100

  # used by `namerctl` to manage configuration
  - kind: io.l5d.httpController
    ip: 0.0.0.0
    port: 4180