version: '3.6'
services:
  linkerd:
    image: buoyantio/linkerd:1.3.7
    ports:
      - 127.0.0.1:9990:9990 # Admin
      - 127.0.0.1:4140:4140 # HTTP
    volumes:
      - $PWD/config/linkerd.yaml:/config.yaml
    command: /config.yaml
  
  web:
    # build: svc
    image: alextanhongpin/linkerd-web
    ports:
      - 127.0.0.1::3000